site_name: Shravan — Software Prototyper
theme:
  name: dracula
  logo: logo.jpg

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
      - Personal:
          - Mememuse: projects/personal/mememuse.md
          - Blawgd: projects/personal/blawgd.md
          - Token Alchemist: projects/personal/token-alchemist.md
          - Portfolio website: projects/personal/portfolio.md
      - Professional:
          - Mempools: projects/professional/mempools.md
          - cw-eth2-lc: projects/professional/electron.md
          - Kyverno: projects/professional/kyverno.md
          - Sigrun: projects/professional/sigrun.md
          - Solcrawl: projects/professional/solcrawl.md
          - Starbreeder: projects/professional/starbreeder.md
  - Skills & Services: skills.md
  - About Me: about.md
  - Contact: contact.md
  - Links: links.md
